version: 1.0.{build}

install: 
  - ps: Start-FileDownload https://raw.githubusercontent.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1
  - ps: Import-Module './vsix.ps1'

build_script:
  - ps: Vsix-IncrementVersion | Vsix-PushArtifacts | Vsix-Build | Vsix-PushArtifacts
