version: 1.0.{build}

configuration: CI
platform: Any CPU

before_build: 
  ps: |
    Invoke-WebRequest https://raw.githubusercontent.com/madskristensen/ExtensionScripts/master/AppVeyor/build.ps1 -OutFile "..\build.ps1"
    ../build.ps1

build:
  verbosity: minimal

artifacts:
- path: '**/*.vsix'
  name: Nightly Build