version: 1.0.{build}

configuration: CI
platform: Any CPU

install: 
  - ps: Invoke-WebRequest https://raw.githubusercontent.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1 -OutFile '.\vsix.ps1'
  - ps: Import-Module './vsix.ps1'

before_build: 
  - ps: Vsix-IncrementVersion

build:
  verbosity: minimal

build_script:
  - msbuild ./**/*.sln /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /logger:'C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll'

artifacts:
- path: '**/bin/$(configuration)/*.vsix'
  name: Nightly Build