version: 1.0.{build}

configuration: CI
platform: Any CPU

install: 
  - ps: Invoke-WebRequest https://raw.githubusercontent.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1 -OutFile '.\vsix.ps1'
  - ps: Import-Module './vsix.ps1'

before_build: 
  - ps: Vsix-IncrementVersion

build:
  verbosity: minimal

artifacts:
- path: '**/bin/$(configuration)/*.vsix'
  name: Nightly Build