version: 1.0.{build}

install: 
  - ps: Start-FileDownload https://raw.githubusercontent.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1
  - ps: Import-Module './vsix.ps1'

before_build: 
  - ps: Vsix-IncrementVersion

build:
  verbosity: minimal

build_script:
  - ps: Vsix-Build -configuration Release|Any CPU

artifacts:
- path: '**/bin/$(configuration)/*.vsix'
  name: Nightly Build