version: 1.0.{build}

configuration: CI
platform: Any CPU

before_build: 
  - ps: Invoke-WebRequest https://raw.githubusercontent.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1 -OutFile '.\vsix.ps1'
  - ps: ./vsix.ps1 -incrementVersion

build:
  verbosity: minimal

artifacts:
- path: '**/bin/$(configuration)/*.vsix'
  name: Nightly Build